### ISSUE TITLE
Documentation of how to use attributes with quote

### ISSUE THREAD

**Issue by spease** [dtolnay/quote#103]
I tried to add `#[allow(clippy::unreadable_literal)]` into string-cache-codegen in order to address some clippy errors. I'm still in the process of debugging, but even though I've specified my git repo and branch in my Cargo.toml, it doesn't seem to be taking. Still looking into this at present, but I couldn't find any examples in the quote documentation to tell if I need to escape the `#` since it's a special character used for variables in quote.

Here's the modified branch as an example of what I'm trying to do:
https://github.com/spease/string-cache/blob/allow-clippy-hash-errors/string-cache-codegen/lib.rs

**Comment by dtolnay** [comment]
You do not need to escape `#` in attributes.

**Comment by dtolnay** [comment]
I've added an example that shows an attribute to show that `#` does not need an escape.

**Comment by spease** [comment]
Very nice thank uou
