### ISSUE TITLE
Generate artificial span information

### ISSUE THREAD

**Issue by mauricekayser** [dtolnay/quote#106]
I am trying to unit test my proc-macro crate: I try to assert whether I set the correct spans in the generated `syn::Error` messages, so they are helpful for the user of my crate and don't point to incorrect locations.

The problem is that the tokens, which `quote!` generates in the unit tests, don't generate their own spans, like the real code that uses my proc-macro crate would have.

The following code:
```rust
let token_stream: proc_macro2::TokenStream = quote::quote!(
    let test: u32 = 0;
);
for token_tree in token_stream.into_iter() {
    let span = token_tree.span();
    let start = span.start();
    let end = span.end();
    println!(
        "Start(Line: {}, Column: {}) + End(Line: {}, Column: {}) for \"{}\"",
        start.line, start.column,
        end.line, end.column,
        token_tree.to_string()
    );
}
```
generates the following output:
```
Start(Line: 1, Column: 0) + End(Line: 1, Column: 0) for "let"
Start(Line: 1, Column: 0) + End(Line: 1, Column: 0) for "test"
Start(Line: 1, Column: 0) + End(Line: 1, Column: 0) for ":"
Start(Line: 1, Column: 0) + End(Line: 1, Column: 0) for "u32"
Start(Line: 1, Column: 0) + End(Line: 1, Column: 0) for "="
Start(Line: 1, Column: 0) + End(Line: 1, Column: 0) for "0"
Start(Line: 1, Column: 0) + End(Line: 1, Column: 0) for ";"
```

This makes it hard to unit test, because I want to test incorrect code, which has to be synthesized and can not be real code, else it would not compile.

For example, if there is something wrong with the `u32` I want to test whether my `syn::Error` message contains the span of it, and not of the `=`, but that doesn't seem to be possible with `quote!`?

Maybe a `quote_generate_span!` could be possible? At least for the `test` profile, because for real code I think it doesn't make sense to generate spans that are outside of real files.

**Comment by dtolnay** [comment]
The best way to test spans in error messages would be using [trybuild](https://github.com/dtolnay/trybuild). Does that do what you need?

**Comment by mauricekayser** [comment]
I would prefer not having to use another crate that does voodoo with extra files instead of everything being in one unit test, so I am not sure whether to omit the span tests or use that crate, but thanks for the link, I will look into it!

**Comment by dtolnay** [comment]
I don't necessarily recommend writing unit tests this way but here is a method to generate distinct spans:

```rust
use proc_macro2::{Span, TokenStream};

fn fake_span(n: usize) -> Span {
    (" ".repeat(n) + "x").parse::<TokenStream>().unwrap().into_iter().next().unwrap().span()
}

fn main() {
    println!("{:?}", fake_span(4).start());
}
```

**Comment by mauricekayser** [comment]
Ok, using a string instead of `quote!` like this:
```rust
let token_stream = "let test: u32 = 0;".parse::<proc_macro2::TokenStream>().unwrap();
```
yields:
```
Start(Line: 1, Column: 0) + End(Line: 1, Column: 3) for "let"
Start(Line: 1, Column: 4) + End(Line: 1, Column: 8) for "test"
Start(Line: 1, Column: 8) + End(Line: 1, Column: 9) for ":"
Start(Line: 1, Column: 10) + End(Line: 1, Column: 13) for "u32"
Start(Line: 1, Column: 14) + End(Line: 1, Column: 15) for "="
Start(Line: 1, Column: 16) + End(Line: 1, Column: 17) for "0"
Start(Line: 1, Column: 17) + End(Line: 1, Column: 18) for ";"
```

Then I will use strings in my unit tests instead, thanks for the hint!
