### ISSUE TITLE
Syntax to append tokens instead of interpolate variables

### ISSUE THREAD

**Issue by keeperofdakeys** [dtolnay/quote#11]
Would it be possible to add a syntax to the `quote!` macro that appends the string contained in a variable as tokens directly, without calling to_tokens first? Or is this already possible, but not documented?

**Comment by dtolnay** [comment]
Depending on which of the following you mean, it may already be possible but not documented:

- You have a string and some tokens and you want to append the string to the tokens.

    ```rust
    let tokens: Tokens = /* ... */;
    let s: String = /* ... */;
    tokens.append(&s);
    ```

    This is how ToTokens implementations are written but I would want to learn more about the use case before documenting this as an intended way of using the library.

- You have a string containing tokens and you want it to get appended as tokens inside a quote macro:

    ```rust
    let s: String = /* ... */;
    quote! {
        q r #??? t u
    }
    ```

    This isn't supported right now unless you can create `s` as Tokens instead of String. You did a good job with this in asn1-cereal-derive using `quote!(None)` instead of `"None"`, for example.

    ```rust
    let s: Tokens = /* ... */;
    quote! {
        q r #s t u
    }
    ```

- You have a string containing something like a variable name and you want it to get appended unquoted inside a quote macro:

    ```rust
    let var: String = /* ... */
    let ident = syn::Ident::new(var);
    quote! {
        let #ident = /* ... */;
    }
    ```

    You could abuse this for the previous case too but that seems like a hack.

I would be interested if you fall into the middle case (or a totally different case) to hear some more details about what you are trying to do, to make sure we come up with the right solution.

**Comment by keeperofdakeys** [comment]
Thanks for the detailed reply. The middle case seems like the closest, then the `class_tokens.append(...)` line wouldn't be needed in my code (https://github.com/keeperofdakeys/asn1-rs/blob/6e25ec/asn1-cereal-derive/src/lib.rs#L47-L48). It is only one line however, so I'd be curious to see how common a pattern this would be. Luckily I've still got plenty of proc macros to write, so I'll see how many more times I come across this as a problem.

**Comment by dtolnay** [comment]
You could turn it into the third bullet this way:

```rust
let class_name = match /* ... */ {
    "ContextSpecific"
};
let class_ident = syn::Ident::new(class_name);
quote! {
    Some(... { class: ::asn1_cereal::tag::Class::#class_ident })
}
```

Another option is:

```rust
let class = match /* ... */ {
    "::asn1_cereal::tag::Class::ContextSpecific"
};
let class_path = syn::parse_path(class).unwrap();
quote! {
    Some(... { class: #class_path })
}
```

**Comment by keeperofdakeys** [comment]
Using `syn` to parse the path seems like the best option here, I didn't realise I could do this. It may provide more accurate error messages as well, if it can't be parsed correctly.

**Comment by dtolnay** [comment]
I filed https://github.com/dtolnay/syn/issues/39 to mention parse_path (and friends) in the syn readme. Serde uses parse_path and parse_where_clause because we need them for parsing [attributes](https://serde.rs/attributes.html#field-attributes) but I wasn't sure whether they would be broadly applicable. Your use case seems like a good fit.

I am closing this out but I am interested to hear back if you find yourself using idioms that don't feel quite right or if you have other suggestions. You are going to be the expert because I have only ever written one proc macro!
