### ISSUE TITLE
New release with fixed tests?

### ISSUE THREAD

**Issue by silwol** [dtolnay/quote#111]
When updating the `quote` Debian package, I ran into tests failing, in https://github.com/dtolnay/quote/commit/b3a3d76815b6f892a86c15da39a3019608290719 they got fixed. Is there any chance to see a release? Otherwise I would add the fix as a patch for now, but of course having a proper upstream release is preferred.
Affected build: https://buildd.debian.org/status/fetch.php?pkg=rust-quote&arch=amd64&ver=0.6.12-1&stamp=1562830665&raw=0

**Comment by dtolnay** [comment]
Sure thing, I published 0.6.13.
