### ISSUE TITLE
Support line break (\n) as a separator for repetitions

### ISSUE THREAD

**Issue by pLesur** [dtolnay/quote#121]
I'm trying to generate human readable code, and for that I would like to add line breaks between e.g struct fields declaration, but it doesn't seem possible at the moment.

For example something like:

```rust
        let fields_quote = quote! {
            #(#modified_field_ref ,)'\n'*
        };
```

**Comment by dtolnay** [comment]
Token streams consist of non-whitespace tokens only. If you need human readable formatting, I would recommend putting the token stream through [rustfmt](https://docs.rs/rustfmt/0.10.0/rustfmt/) or else using something string based rather than token based to produce the output.

**Comment by pLesur** [comment]
Hmm I see, thanks for the tips

**Comment by pjenvey** [comment]
In case anyone references this issue (like I just did), nowadays there's dtolnay's `prettyplease` crate or alternatively the `rustfmt-wrapper` crate.
