### ISSUE TITLE
Interpolation for #[link_name]

### ISSUE THREAD

**Issue by michaelvoronov** [dtolnay/quote#127]
I have stumbled with a problem of interpolation in the link directive. More precisely, i am trying to implement this [one](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=84f9aa5fe53b656001c5794bf4cf9555) with proc macro. And I am getting the `error: unexpected token: sqlite_allocate` error [here](https://github.com/fluencelabs/fluence/blob/side_modules_attrs/backend-sdk/crates/macro/src/lib.rs#L225). I have read comments comments [here](https://github.com/dtolnay/quote/blob/master/src/lib.rs#L382), but it (with `Ident` instead of `Expr`) hasn't worked also. I must be doing something wrong, could you give some points of direction?

Thank you in advance!

**Comment by dtolnay** [comment]
Your proc macro is generating `#[link_name = sqlite_allocate]` which is not valid syntax. You need to make it generate `#[link_name = "sqlite_allocate"]` by interpolating the String, not an Ident or Expr.

**Comment by michaelvoronov** [comment]
It works, thank you!
