### ISSUE TITLE
Best way to convert Option<T> to tokens?

### ISSUE THREAD

**Issue by aclysma** [dtolnay/quote#129]
First, thanks for answering so many proc_macro questions. The existing issues here with excellent responses have been extremely helpful.

I have a bit of code I was able to get working, but I'm wondering if this is the intended way to implement this? I think it's similar to #94 

(I put comments in code because I think my question is clearer this way)

```
// ***** I want the proc_macro to generate a const of this type
#[derive(Debug)]
struct InspectArgs {
    min_value: Option<f32>,
    max_value: Option<f32>,
    step: Option<f32>,
}

// ***** I expected Option<T> to expand to None(t) or Some(t), but it does not.
// So I implemented a helper function to do that
fn expand_to_tokens<T : quote::ToTokens>(input: &Option<T>) -> proc_macro2::TokenStream {
    match input {
        Some(value) => quote!(Some(#value)),
        None => quote!(None)
    }
}

impl quote::ToTokens for InspectArgs {
    fn to_tokens(&self, tokens: &mut proc_macro2::TokenStream) {
        // ***** This works, but I feel like there might be a better solution
        let min_value = expand_to_tokens(&self.min_value);
        let max_value = expand_to_tokens(&self.max_value);
        let step = expand_to_tokens(&self.step);

        use quote::TokenStreamExt;
        tokens.append_all(quote!(
            InspectArgs {
                min_value: #min_value,
                max_value: #max_value,
                step: #step,
            }
        ));
    }
}
```

**Comment by dtolnay** [comment]
What you wrote is the intended way to implement this.

Be aware that `Some` and `None` may not refer to variants of `std::option::Option` in the caller's code. For example they could have:

```rust
use pyo3::PyErrValue::*;

your_macro!();
```

So it would be more correct to emit them as `std::option::Option::Some` / `std::option::Option::None`.

**Comment by aclysma** [comment]
Thanks!

**Comment by mystor** [comment]
> So it would be more correct to emit them as `std::option::Option::Some` / `std::option::Option::None`.

It would also generally be correct to emit them as `core::option::Option::{Some,None}` for `#![no_std]` support, if that's valuable for your custom derive.
