### ISSUE TITLE
Generate artificial span information, including source code

### ISSUE THREAD

**Issue by edulix** [dtolnay/quote#132]
Is there any way to generate errors nicely like rust does, that reference the source code and span information, when the code is being embed with `quote!()` inside a macro that loads that code from an external file?

Context: I'm loading some code from a yaml file within a macro. The file is loaded with serde, and then the macro generates some code with `quote` taking in some cases rust code input directly from the yaml file. I know it sounds a bit crazy but that's what I need to do.

I wouldn't mind using something like `codespan`, but the best I think I can manage to do is to show an error referencing the first line of the source code using serdes' "deserialize_with" as proposed by @dtolnay  in https://github.com/alexcrichton/toml-rs/issues/236#issuecomment-386837860 . Which is not ideal although it's a start.

Currently I've got it even worse. the errors I get are similar to this (does not even reference the source code line, as it is from a yaml file):

```rust
error[E0616]: field `name` of struct `Misc` is private
 --> my_project/tests/a_test/main.rs:7:1
  |
7 | load_file!("my_project/tests/a_test/main.yml");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
```

**Comment by dtolnay** [comment]
Currently only files that are loaded and parsed by rustc are given spans that make sense in diagnostics drawn by rustc. If the compiler isn't the one parsing the file, you would need to draw the diagnostics yourself using something like codespan and [`Span::start`](https://docs.rs/proc-macro2/1.0.2/proc_macro2/struct.Span.html#method.start) / [`Span::end`](https://docs.rs/proc-macro2/1.0.2/proc_macro2/struct.Span.html#method.end).

**Comment by dtolnay** [comment]
https://github.com/dtolnay/cxx/blob/0.1.0/gen/error.rs shows an example of codespan-based diagnostics.

```console
error[cxxbridge]: returning opaque Rust type by value is not supported

    ┌── demo-rs/src/main.rs:13:22 ───
    │
 13 │         fn test() -> ThingR;
    │                      ^^^^^^ returning opaque Rust type by value is not supported
    │
    = hint: wrap it in a Box<>
```

**Comment by edulix** [comment]
Thanks, sorry for not answering before.
