### ISSUE TITLE
Extend `quote` macro for use in `ToTokens`

### ISSUE THREAD

**Issue by Popog** [dtolnay/quote#136]
https://github.com/dtolnay/quote/issues/94#issuecomment-458046932 suggests a pattern to implement `extend` and `quote!`.

It seems like it would be more intuitive to have a variant of the `quote` macro which takes a `&mut TokenStream` as a parameter.

Use of it would look something like:

```rust
use proc_macro2::TokenStream;
use quote::{quote, ToTokens};

struct Datum(u8);
struct Data(Vec<Datum>);

impl ToTokens for Data {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let d = self.0.iter().map(|datum| datum.0);
        quote_extend!{tokens=>
                Data(<[Datum]>::into_vec(Box::new([ #( Datum(#d) ),* ])))
        }
    }
}

fn main() {
    let d = Data(vec![Datum(2), Datum(4), Datum(6)]);
    println!("{}", quote!(#d));
}
```

I'd be willing to put together a PR for this if there's any interest.

**Comment by dtolnay** [comment]
I don't understand why:

```rust
quote_extend!{tokens=>
    ...
}
```

is better than:

```rust
tokens.extend(quote! {
    ...
});
```

**Comment by Popog** [comment]
🤷, it's kinda hard for me to say why I think it feels more intuitive, but I just have some gut feeling about it.

One contributing factor I can identify is: a separate API will communicate the specific use case in the most explicit way possible.

From an implementation efficiency perspective it can also avoid the temporary allocation.

**Comment by dtolnay** [comment]
Thanks for the PR in #137, but I would prefer not to add this API.
