### ISSUE TITLE
Output of `quote!` does not permit method call

### ISSUE THREAD

**Issue by BatmanAoD** [dtolnay/quote#139]
I don't know if this can be fixed (or if it's worth fixing), but I didn't see it in the documentation or in an existing issue.

This works:

```
#[proc_macro_attribute]
pub fn add_dummy(_attr: TokenStream, _item: TokenStream) -> TokenStream {
    TokenStream::from(quote!{
        struct Dummy;
    })
}
```

This fails to compile:

```
#[proc_macro_attribute]
pub fn add_dummy(_attr: TokenStream, _item: TokenStream) -> TokenStream {
    quote!{
        struct Dummy;
    }.into()
}
```

...with the following error (in 1.38):

```
error: expected expression, found `.`

  --> src/lib.rs:51:6
   |
51 |     }.into()
   |      ^ expected expression

error[E0308]: mismatched types
  --> src/lib.rs:49:5
   |
49 | /     quote!{
50 | |         struct Dummy;
51 | |     }.into()
   | |_____^ expected (), found struct `proc_macro2::TokenStream`
   |
   = note: expected type `()`
              found type `proc_macro2::TokenStream`
```

I'm not sure why the syntax element produced by `quote!` is permissible as a function argument but not as a method receiver, but this was a bit surprising to me.

**Comment by dtolnay** [comment]
This is how macro invocations with !{...} always work. If you need a trailing method call you would need to use !(...).

```rust
quote!(
    ...
).into()
```
```

**Comment by BatmanAoD** [comment]
Well, I feel very silly for not realizing that. Thanks!
