### ISSUE TITLE
Tokens::as_str(&self) -> &str ?

### ISSUE THREAD

**Issue by SimonSapin** [dtolnay/quote#14]
What do you think of adding a method to borrow `&str` from `&Tokens`? Currently the `to_string()` method (through `std`’s `Display` and `ToString` traits) can be used, but it involves a memory allocation and copy that could be avoided in some cases.

The downside is that this would lock in place the current memory representation of `Tokens` (a single `String`). But is there any plan to change it?

**Comment by dtolnay** [comment]
You're right, I am pretty comfortable locking in the representation at this point. I released this in 0.3.7.
