### ISSUE TITLE
Support nested usages of quote

### ISSUE THREAD

**Issue by canndrew** [dtolnay/quote#142]
I'm writing a proc macro for use in proc macros. I'd like to write some code that looks like this:

```rust
let foo = ... ;
quote! {
    let bar = ... ;
    quote! {
        (#foo, ##bar)
    }
}
```

ie. where `foo` gets expanded when my proc macro runs and `bar` gets expanded when the proc macro that uses my proc macro runs. This doesn't seem possible though. Maybe I've just incorrectly guessed the syntax, but I couldn't find anything when searching the docs and the issue tracker for "nesting".

**Comment by dtolnay** [comment]
`##bar` means `#` followed by `#bar`. If you want `#` followed by `bar` you could write:

```rust
let pound = Punct::new('#', Spacing::Alone);
quote! {
    quote! {
        (#foo, #pound bar)
    }
}
```

Alternatively you could write:

```rust
use proc_macro2::{Ident, Punct, Spacing, Span, TokenStream};
use quote::{quote, ToTokens, TokenStreamExt};

struct Interp(&'static str);

impl ToTokens for Interp {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        tokens.append(Punct::new('#', Spacing::Alone));
        tokens.append(Ident::new(self.0, Span::call_site()));
    }
}

const BAR: Interp = Interp("bar");

...

quote! {
    quote! {
        (#foo, #BAR)
    }
}
```

**Comment by canndrew** [comment]
Thanks, and thanks for the quick response :)

> `##bar` means `#` followed by `#bar`.

Right. I can see my syntax can't be made to work.

> If you want `#` followed by `bar` you could write:

Thanks. I'll do that.
