### ISSUE TITLE
Escape hatch for reusing other non-std iterable types

### ISSUE THREAD

**Issue by CAD97** [dtolnay/quote#145]
In a proc macro I'm currently working on, I've collected an [`IndexSet`](https://docs.rs/indexmap/1.3.2/indexmap/set/struct.IndexSet.html)`<Ident>`, and want to use it in a quote like the following:

```rust
let kws = self.custom_keywords.iter();

quote! {
    pub mod kw {
        #(::pegcel::crates::syn::custom_keyword!(#kws);)*
    }

    #[doc(hidden)]
    macro_rules! #token_macro {
        #((#kws) => {self::kw::#kws};)*
        ($($tt:tt)*) => {::pegcel::crates::syn::Token![$($tt)*]};
    }

    pub use #token_macro as Token;
}
```

This doesn't work as written (and correctly gives a compile error), as `kws` cannot be used by two distinct quote loops, because it is not `Copy`. Of course, the collection itself does not have a `quote_into_iter` function because it does not implement `RepIteratorExt` nor `RepToTokensExt`.

There are two current workarounds I know work:
- Collect everything into a `Vec<_>`, as it can be used like this,
- Use a `BTreeSet`, changing the output order from input order to sorted order (only works because `Ident: Ord`; would not work with a type that is not), or
- Create a different `.iter()` for each distinct quote iteration in the quote invocation.

The latter is sub-optimal, because the two iterators have no guarantee that they are the same. The former works, and is what I'm using currently, though it feels like a workaround that just exists because `quote` doesn't work as well with non-std collections.

A potential way I thought of for quote to support non-std "iterables" (i.e. types with a `fn iter(&self) -> impl Iterator + '_`) is to work with closures (i.e. `impl Fn() -> impl RepIteratorExt`).

Testing this myself, the naive solution of `impl<'q, 'a, F: (Fn() -> I) + 'a, I: RepIteratorExt> RepAsIteratorExt<'q> for F` obviously (in retrospect) doesn't work because the impl potentially conflicts with `&_`. I was, however, able to get it to work with dyn trait objects:

```rust
    impl<'q, 'a, I: RepIteratorExt> RepAsIteratorExt<'q> for dyn (Fn() -> I) + 'a {
        type Iter = I;

        fn quote_into_iter(&'q self) -> (Self::Iter, HasIter) {
            (self(), HasIter)
        }
    }
```

which is then used with `let kws: &dyn Fn() -> _ = &|| self.custom_keywords.iter();` (the type annotation is, unfortunately, required).

I don't know whether this is simple enough to carry it's weight; while just making a closure work might be worth it, this feels undiscoverable enough that most would probably just use the collect-to-`Vec` solution, which is simple, even if not ideologically elegant. I do, however, think it's worth sharing this little bit of thought and experimentation, thus this issue.

`IndexSet`/`IndexMap` feel like a great choice in proc macros because of their deterministic input ordering. It's just sad that they're not possible to use the same way as a std collection (that is, repeated interpolation).

**Comment by dtolnay** [comment]
I think this is all right as currently implemented. Both of the following are better than `let kws: &dyn Fn() -> _ = &|| self.custom_keywords.iter()` in my opinion:

```rust
let kws = Vec::from_iter(&self.custom_keywords);
```

```rust
let kws1 = self.custom_keywords.iter();
let kws2 = kws1.clone();
```

**Comment by CAD97** [comment]
Knowing what I know today, I think I'd ask for it to check `&T: IntoIterator` before `T: IntoIterator` to allow non consuming iteration more generally, but I agree in general that this is low priority since there's a simple way to get the desired functionality.
