### ISSUE TITLE
"error: expected pattern, found `,`" upon compiling quote!({ # for })

### ISSUE THREAD

**Issue by iptq** [dtolnay/quote#146]
```rs
#[macro_use]
extern crate quote;

fn main() {
    println!("{:?}", quote!({ # for }));
}
```

This snippet makes the compiler blow up with this message:

```
error: expected pattern, found `,`
 --> src/main.rs:5:22
  |
5 |     println!("{:?}", quote!({ # for }));
  |                      ^^^^^^^^^^^^^^^^^ expected pattern
  |
  = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

Is there something special about the pound sign that makes it not work with the for-keyword? (Replacing the pound sign and the for keyword separately makes it behave as expected.) I tried expanding the macro but did not find anything out of the ordinary.

**Comment by dtolnay** [comment]
The pound sign is used for interpolating variables, and `for` is not a valid name for a variable so I'm not surprised at the error when using it as one.

**Comment by iptq** [comment]
oh my god i'm an idiot
