### ISSUE TITLE
could not find `__rt` in `quote`

### ISSUE THREAD

**Issue by mbaneshi** [dtolnay/quote#147]
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /Users/**/.cargo/registry/src/github.com-1ecc6299db9ec823/err-derive-0.1.6/src/lib.rs:145:63
    |
145 | fn display_body(s: &synstructure::Structure) -> Option<quote::__rt::TokenStream> {
    |                                                               ^^^^ could not find `__rt` in `quote`

**Comment by dtolnay** [comment]
This was a bug in err-derive that they fixed in https://gitlab.com/torkleyy/err-derive/-/merge_requests/19.
