### ISSUE TITLE
Recursion limit reached

### ISSUE THREAD

**Issue by Arnavion** [dtolnay/quote#15]
rustc 1.14.0-nightly (cae6ab1c4 2016-11-05) on Windows 7
quote v0.3.5
syn v0.10.0

```rust
#[macro_use]
extern crate quote;
extern crate syn;

fn main() {
	let struct_name = syn::Ident::from("Foo".to_string());

	quote! {
		fn visit_str<E>(&mut self, v: &str) -> ::std::result::Result<Self::Value, E> where E: ::serde::Error {
			let fixed_version = v;
			::semver::Version::parse(&fixed_version).map_err(|err| ::serde::Error::invalid_value(::std::error::Error::description(&err)))
		}
	};
}
```

```
$ cargo build

error: recursion limit reached while expanding the macro `stringify`
  --> src\main.rs:8:2
   |
8  |    quote! {
   |    ^
   |
   = note: this error originates in a macro outside of the current crate

error: Could not compile `test`.
```

This is the smallest I can make the test case that still repros, so it's not valid code. The original unreduced code is a much longer proper impl of serde::Deserialize.

Edit: I've worked around it by setting the recursion_limit crate attribute. So if there's nothing obvious in how quote! expands that can be fixed, I'm okay with that workaround. (I was just surprised it triggered on such simple code.)

**Comment by dtolnay** [comment]
Just bump up the recursion limit:

```rust
#![recursion_limit = "128"]
```

We've been using 192 in serde and it still compiles much faster than it used to with the `quasi` crate. The whole `quote!` macro is implemented using macro_rules so there isn't really a way around this.

I will add a note in the readme.

**Comment by Arnavion** [comment]
Yeah, that's what I did.

**Comment by dtolnay** [comment]
Cool. I am closing the issue because I don't intend to fix it. Maybe when procedural macros are stable I can reimplement `quote!` in a better way but for now I just put a note about recursion limit in the readme.
