### ISSUE TITLE
Provide a way to directly write newlines and comments

### ISSUE THREAD

**Issue by sdroege** [dtolnay/quote#154]
Currently this is possible only by storing `proc_macro2::Punct` in a variable and interpolating that into a `quote! { ... }` block. It would be nice have a nicer way for this.

While functionally it doesn't make any difference, it could make the generated code more readable for debugging purposes and also allows to use `quote` as a general code generation mechanism outside of proc macros.

**Comment by dtolnay** [comment]
I would prefer not to build this into quote, but there is room in the ecosystem for a different library geared toward this use case.

FWIW https://github.com/dtolnay/syn/blob/1.0.19/src/gen/fold.rs is produced using quote, including newlines and doc comments so it's possible to use as a general code generation mechanism outside of proc macros.

**Comment by sdroege** [comment]
Fair enough. That code you pasted there shows the exact problem though: densely packed without any empty lines between things, not readable at all :)

I'll continue to interpolate newlines into `quote! { ... }` blocks then for the meantime, it's not worth creating a new macro around `quote` just for this.
