### ISSUE TITLE
Feature: pretty-printing the quote output

### ISSUE THREAD

**Issue by vorner** [dtolnay/quote#155]
Hello

I'm not sure this is for the quote crate to handle or if this should go somewhere else. I'm using quote to conveniently generate code from my `build.rs`, something like this:

```rust
let mut output = File::create(...).unwrap();
let tokens = quote! {
  println!("Hello {}", #name);
};
writeln!(output, "{}", tokens).unwrap();
```

It works well enough in practice and shields me from having to escape bunch of `{}` if I just used `writeln!` directly with some interpolation.

The one issue I have is, the output is always one-line spaghetti and if I manage to generate a code that doesn't compile, neither the error messages nor the generated code are convenient to read.

So I was thinking if there was some way to format the tokens before being written into the file ‒ either as a feature bringing in some other dependency, or maybe linking it from the readme how to do that, it would be great.

**Comment by dtolnay** [comment]
I would prefer not to build anything for pretty printing into quote; but rustfmt has a pretty printer that you can apply to the generated code. For example https://github.com/dtolnay/syn/blob/1.0.20/src/gen/visit.rs is generated by quote + rustfmt.

**Comment by vorner** [comment]
> I would prefer not to build anything for pretty printing into quote

Understood.

In the end I went with calling `rustfmt` as an external command (and not failing if it's not available). As a library it seems to need nightly, at least according to documentation.

Anyway, would you mind if I tried adding a section to readme discussing usage outside of proc macros and hints like using rustfmt for pretty-printing things?

**Comment by dtolnay** [comment]
I added a brief note. I would be on board with documenting a bit more if there are aspects that are hard to discover, but I don't want to dedicate that much of the readme to this use case.
