### ISSUE TITLE
How to generate different function for different type?

### ISSUE THREAD

**Issue by uuhan** [dtolnay/quote#165]
I'am a newbie to use proc-macro, and how can I generate different function for different type, like this:

```rust
    ...
    let field_type = input.fields.iter().map(|field| &field.ty);

    let output = quote! {
          // pseude code:
          // #if #field_type == i32 {
          //      pub fn fun1() -> #field_type { // i32 logic here }
          // } #else {
          //      pub fn fun1() -> #field_type { // another logic here }
          // }
    }
    ...
```

**Comment by botika** [comment]
That is not possible. You could do something like this.
```rust
let field_type: TokenStream = input.fields.iter().map(|field| &field.ty)
    .map(|ty| {
       if ty.to_string() == "i32" { quote!(...) } else { quote!(...) }
     })
    .flatten()
    .collect();
```

You have a lot of documentation and forums like https://users.rust-lang.org/ where they will give you the solution for these simpler questions.

**Comment by dtolnay** [comment]
Sorry I didn't get a chance to respond. If this is still an issue, you could try taking this question to the Rust Discord, Zulip, the \[rust\] tag on StackOverflow, or the /r/rust subreddit which has a pinned weekly questions post.
