### ISSUE TITLE
Can Replace code token?

### ISSUE THREAD

**Issue by zhuxiujia** [dtolnay/quote#168]
First of all, I want to say that this library is really great。

When Generating the code, I defined Ident and Tokenstream first, and then used the Quote macro to compose the code. Could you use the quote macro to generate a template and then replace some of its contents by ident and Tokenstream?

**Comment by dtolnay** [comment]
This is not supported and I would prefer not to build something like this into `quote`, but it would be reasonable for someone to make a separate crate implementing this approach.

**Comment by chesedo** [comment]
@zhuxiujia I needed something similar recently and created the crate [`tokenstream2-tmpl`](https://crates.io/crates/tokenstream2-tmpl). I am still not too happy with the "markers" it is using though. So any suggestions for improvements are welcome...
