### ISSUE TITLE
Integer types suffix should be separated by underscore

### ISSUE THREAD

**Issue by clinta** [dtolnay/quote#170]
Quote generates integer literals with the type suffix in the format `42u32`, [clippy](https://rust-lang.github.io/rust-clippy/master/index.html#unseparated_literal_suffix) says it should be in the format `32_u32`.

**Comment by clinta** [comment]
Related is clippy [unreadable literal](https://rust-lang.github.io/rust-clippy/master/index.html#unreadable_literal), it would be nice if Quote generated literals in this format as well.

**Comment by dtolnay** [comment]
This needs to be fixed in clippy. We're just using rustc's [proc_macro::Literal::u32_suffixed](https://doc.rust-lang.org/1.46.0/proc_macro/struct.Literal.html#method.u32_suffixed) etc. It shouldn't be linting generated code.
