### ISSUE TITLE
Getting struct members in quote macro

### ISSUE THREAD

**Issue by thorlucas** [dtolnay/quote#171]
Simply this:

```rust
struct Bar { ... }

impl ToTokens for Bar { ... }

struct Foo {
    pub bar: Bar,
}

// ...

let foo: Foo = ...;

let q = quote! {
    blah blah #{foo.bar}.baz
};
```

This isn't possible it seems. Instead, we have to do something like this:

```rust
let foo: Foo = ...;
let bar: Bar = foo.bar.clone();

let q = quote! {
    blah blah #bar.baz
};
```

Which is very messy and for large quotes requires a lot of doing that. Plus it's expensive as we have to clone a lot of things. And finally it only works if `Bar` is `Clone`.

**Comment by taiki-e** [comment]
> Which is very messy and for large quotes requires a lot of doing that. Plus it's expensive as we have to clone a lot of things. And finally it only works if `Bar` is `Clone`.

You can use reference instead of clone: 
```rust
let foo: Foo = ...;
let bar: Bar = &foo.bar;

let q = quote! {
    blah blah #bar.baz
};
```

**Comment by dtolnay** [comment]
Yes -- please write this using a reference as shown in the previous comment.

**Comment by botika** [comment]
@thorlucas  Or you can use for cleaner code:

```rust
let Foo { bar, ... } = &structure;

let q = quote! {
    blah blah #bar.baz
};
```
