### ISSUE TITLE
try_format_ident!() -> Result<()>

### ISSUE THREAD

**Issue by ctaggart** [dtolnay/quote#172]
Would it be possible to add a function similar to `format_ident!()` that returns a `Result` instead of panicking if the string is not valid? ❤️

**Comment by dtolnay** [comment]
I think I would prefer not to add this. For now you can get the same effect using syn::parse_str::\<Ident\>.

**Comment by ctaggart** [comment]
I will look into `syn::parse_str::<Ident>`. Thanks!
