### ISSUE TITLE
Error while compilling for arm/android

### ISSUE THREAD

**Issue by Deshdeepak1** [dtolnay/quote#174]
Compiling as a dependency of menyoki  shows this error .

Compiling quote v1.0.7
error[E0412]: cannot find type `DeviceState` in this scope
  --> /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/device_query-0.2.7/src/lib.rs:39:22
   |
39 | impl DeviceQuery for DeviceState {
   |                      ^^^^^^^^^^^ not found in this scope

**Comment by dtolnay** [comment]
This doesn't have anything to do with quote. That error is in the device_query crate.
> /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/device_query-0.2.7/src/lib.rs:39:22

**Comment by Deshdeepak1** [comment]
Is there a way to fix this?
