### ISSUE TITLE
Expose the quote::quote_each_token macro as something like quote_into!()

### ISSUE THREAD

**Issue by coolreader18** [dtolnay/quote#177]
If this were exposed, users of the crate would be able to easily directly extend an existing token stream, rather than creating a new one an immediately deallocating it. It might not matter all that much, given that the root of a token stream doesn't have all that many TokenTrees in it (i.e. `quote!(impl Foo { /* 1000 lines of code */ }).into_iter().count() == 3`) but given that the functionality already exists, I think it couldn't hurt to expose it. Something that looks like:

```rust
let mut output = input.into_token_stream();

for x in impls_or_extra_type_decls {
    let (a, b, c) = x;
    quote_into! { output,
        ... #a ... #b ... #c
    }
}

output.into()
```

**Comment by dtolnay** [comment]
As you said, it doesn't make a difference, so I would prefer not to expose an additional API for this.
