### ISSUE TITLE
Emojis not quoted correctly

### ISSUE THREAD

**Issue by SirWindfield** [dtolnay/quote#179]
Expected outcome: ⬆️
Produced outcome: ⬆\u{fe0f}

It is the same Unicode character though. Is this intentional behavior or a bug in quote? I'd expect the outcome to be the emoji itself ⬆️ and not the bytes it is made out of.

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d00f97231cc04dd646c7f6a7ad98b02d

**Comment by dtolnay** [comment]
Quote doesn't do any escaping, so I don't think this can be an issue in quote.

**Comment by SirWindfield** [comment]
Is it somehow possible to force quote to quote the unicode character (`⬆️`) and not the bytes alone (`⬆\u{fe0f}`)

**Comment by dtolnay** [comment]
Once again, the thing putting in the \u escape sequence is not quote, so no. Quote only turns the input variables into tokens, which does not involve any escaping. Presumably whatever is turning the tokens into printed output is where the escape sequence comes from.

**Comment by SirWindfield** [comment]
Ah OK, I got you. I didn't understand it first! Thanks for answering me!

**Comment by pheki** [comment]
For future reference: it's proc-macro2 escapes the input using `char::escape_default` on Literal creation.

Sources:
- [`str::to_tokens` in quote bdb4b59](https://github.com/dtolnay/quote/blob/bdb4b594076d78127b99a3da768e369499e324de/src/to_tokens.rs#L117-L117)
- [`Literal::string` in proc-macro2 e94f432](https://github.com/dtolnay/proc-macro2/blob/e94f4326bdd5a94e16be6da362af2e31bea52583/src/fallback.rs#L1027)
