### ISSUE TITLE
How do I format and display TokenStream content

### ISSUE THREAD

**Issue by zhuxiujia** [dtolnay/quote#182]
How do I format and display TokenStream content？
Because the generated code is messy

for example(Here is the generated code snippet):
```rust
 { sql = sql + " and name like #{pattern} " ; } sql = format !
    ("{}{}", sql, "(") ; let trim_string_prefix =
    {
        let mut sql = String :: new() ; sql = sql + " and id!=null and " ; sql
        = sql . trim_start() . to_string() ; if sql . starts_with("and")
        { sql = sql . trim_start_matches("and") . to_string() ; } sql
    } ; sql = sql + trim_string_prefix . as_str() ; let sql_trim = sql .
    trim() ; if sql_trim . ends_with("and")
    { sql = sql_trim . trim_end_matches("and") . to_string() ; } sql = sql +
    ")" ; return(sql, args) ;
```

**Comment by taiki-e** [comment]
proc-macro does not provide such functionally, but you can format generated code by calling rustfmt, like [cargo-expand does](https://github.com/dtolnay/cargo-expand/blob/b20527c325b0f8fcf4a657a35648dd65ead10ef2/src/main.rs#L209).

**Comment by dtolnay** [comment]
Yeah this crate doesn't reimplement a Rust formatter. You can run rustfmt on the result if you need formatted source code. Check out https://github.com/dtolnay/syn/blob/1.0.82/codegen/src/file.rs for an example.
