### ISSUE TITLE
Investigate `proc_macro::quote_span` integration

### ISSUE THREAD

**Issue by Aaron1011** [dtolnay/quote#184]
With PR https://github.com/rust-lang/rust/pull/84278, Rust now has the ability to quote a `Span` to a `TokenStream`. This allows us to obtain spans pointing into a proc-macro crate:

```
error[E0412]: cannot find type `MissingType` in this scope
  --> $DIR/auxiliary/span-from-proc-macro.rs:37:20
   |
LL | pub fn error_from_attribute(_args: TokenStream, _input: TokenStream) -> TokenStream {
   | ----------------------------------------------------------------------------------- in this expansion of procedural macro `#[error_from_attribute]`
...
LL |             field: MissingType
   |                    ^^^^^^^^^^^ not found in this scope
   |
  ::: $DIR/span-from-proc-macro.rs:8:1
   |
LL | #[error_from_attribute]
   | ----------------------- in this macro invocation
```

Currently, this is integrated with the unstable `proc_macro::quote!` macro. However, as virtually everyone uses the `quote` crate instead, it would be nice to add span-quoting support here (behind a nightly feature).

The span-quoting API is used via [`proc_macro::quote_span`](https://doc.rust-lang.org/nightly/proc_macro/fn.quote_span.html), and produces a `TokenStream`. I've provided an example of using it [here](https://github.com/rust-lang/rust/blob/2a245f40a19c9a60b3be33c959eb5cfb0ad163c6/src/test/ui/proc-macro/auxiliary/custom-quote.rs).

I'm not sure how to best way to integrate this API into the `quote` crate, since it looks like a `Span` parameter isn't passed around in many places (presumably for performance reasons). However, I'd be happy to work on a PR if you support the overall idea, and know the general shape of the modifications that you'd like.

**Comment by Aaron1011** [comment]
cc @dtolnay - does the overall idea of supporting this in `quote` sound reasonable?

**Comment by dtolnay** [comment]
If I understand correctly, you are asking to reimplement `quote` as a procedural macro? If so, I am not interested in that. I think the benefits of this change would be minor or nonexistent for typical users of this crate and the compile time cost would greatly outweigh it in comparison.

**Comment by Aaron1011** [comment]
It should be possible to get most of the benefit of `quote_span` without re-implementing the `quote` crate. Instead, a helper proc-macro crate would be used to implement `push_ident`:

https://github.com/dtolnay/quote/blob/cbe5dedaebec70480fde8c6f88f7f691c89f0db3/src/lib.rs#L1047-L1049

We would pass the captured `$ident` metavariable to the proc-macro:

```rust
quote_helper::quote_with_span!($ident)
```

The macro implementation would call `proc_macro::quote_span` with the `Span` taken from its input `TokenStream`. As a result, `quote_with_span!($ident)` would expand to something like `Ident::new(<literal_ident_contents>, ::Span::recover_proc_macro_span(...))`

This would allow the rest of `quote` to remain unchanged. We wouldn't be able to quote spans for the various operators special-cased by `quote_token`, but it should be enough to get many error messages to point to the proper place within a proc-macro crate.

**Comment by dtolnay** [comment]
Nice, that sounds promising -- but I would like this to be done as a different crate for now.

**Comment by dtolnay** [comment]
I'll close since I am not planning on pursuing this in `quote` for now. I am interested to hear how it goes in a different crate though.
