### ISSUE TITLE
"*" cannot be used as a seperator

### ISSUE THREAD

**Issue by Volker-Weissmann** [dtolnay/quote#186]
`#(#var),*` produces `a,b,c`, but `#(#var)**` does work. How can I produce `a*b*c`?

Currently, I use `#((#var) *)* 1.0`, but this is not a perfect solution

**Comment by dtolnay** [comment]
The expansion to `a b c *` matches the behavior of macro_rules, so I think this is fine.

```rust
macro_rules! repro {
    ($($var:tt),*) => {
        stringify!($($var)**)
    };
}

fn main() {
    println!(repro!(a, b, c));
}
```

An alternative in both cases would be something like:

```rust
let mut rest = var.iter();
let first = rest.next();
quote! { #first #(* #rest)* }
```

**Comment by Volker-Weissmann** [comment]
> ```rust
> let mut rest = var.iter();
> let first = rest.next();
> quote! { #first #(* #rest)* }
> ```

Thank you, this is what I needed.
