### ISSUE TITLE
Interpolate Option

### ISSUE THREAD

**Issue by Keats** [dtolnay/quote#20]
I create an enum while parsing a struct with this signature: `{min: Option<u64>, max: Option<u64>, equal: Option<u64>}`.

I want to re-create that object inside `quote!` later on but interpolation #min or any other field will show the value and nothing for `None`.

Am I missing something?

**Comment by dtolnay** [comment]
This is a tricky case. Both implementations ("Some(t)"/"None" vs "t"/"") are useful in different cases.

I went with the approach that libsyntax's quasi-quoter takes [here](https://github.com/rust-lang/rust/blob/1.14.0/src/libsyntax/ext/quote.rs#L66-L73), which is the behavior you saw. Just the value if it is Some, and nothing if it is None. You can imagine this being useful for functions / statements / keywords that you sometimes don't need, which is how we use it within Serde. For example you might have a variable that needs to be mutable if n>0 and immutable if n==0, and we represent the mutability as Some("mut") or None and put it in the right place.

One major reason that I prefer the current approach is that there is no foolproof way for macros to refer to standard library paths, so I would like to avoid baked-in assumptions as much as possible and force you to do the right thing for your use case. Some use cases need "::std::option::Option::Some(t)" and "::std::option::Option::None". Or if building with no_std, they need "::core::option::Option::Some(t)" and "::core::option::Option::None". Or if type inference needs some help, they may need "::std::option::Option::None::\<T>".

If the behavior you expected is something you need often in your program, you can get it by implementing ToTokens for your own wrapper type like in the code below. Alternatively you could write a helper function `fn quote_option<T>(opt: &Option<T>) -> Tokens` to do this, then use the result of that inside your original `quote!` expression.

```rust
#[macro_use]
extern crate quote;

use quote::{Tokens, ToTokens};

struct QuoteOption<T>(Option<T>);

impl<T> ToTokens for QuoteOption<T>
    where T: ToTokens
{
    fn to_tokens(&self, tokens: &mut Tokens) {
        tokens.append("::");
        tokens.append("std");
        tokens.append("::");
        tokens.append("option");
        tokens.append("::");
        tokens.append("Option");
        tokens.append("::");
        match self.0 {
            Some(ref t) => {
                tokens.append("Some");
                tokens.append("(");
                t.to_tokens(tokens);
                tokens.append(")");
            }
            None => {
                tokens.append("None");
            }
        }
    }
}

fn main() {
    let some = QuoteOption(Some(5));
    let none = QuoteOption(None::<u8>);

    println!("{}", quote!(#some != #none));
}
```

**Comment by Keats** [comment]
Make sense, I ended up building my own `Tokens` for my case as I only have one kind of option so far.
Thanks!

**Comment by rbalicki2** [comment]
This didn't seem to work for me (perhaps because I'm on nightly, or on a different version, or what-have-you.) But the following modification of @dtolnay 's code worked for me!

https://gist.github.com/rbalicki2/84d1a7b4febe64e153cbfe52419dcbf1

The errors I had were of the following type:

```rs
   |
25 |                 tokens.append("Some");
   |                        ^^^^^^ the trait `std::convert::From<&str>` is not implemented for `proc_macro2::TokenTree`
```

**Comment by dtolnay** [comment]
The difference is my comment from 2016 was against the quote 0.3 API. Today in 0.5 I would implement the same thing as:

```rust
impl<T: ToTokens> ToTokens for QuoteOption<T> {
    fn to_tokens(&self, tokens: &mut Tokens) {
        tokens.append_all(match self.0 {
            Some(ref t) => quote! { ::std::option::Option::Some(#t) },
            None => quote! { ::std::option::Option::None },
        });
    }
}
```

**Comment by flying-sheep** [comment]
Maybe quote should just provide `QuoteOption`. Full definition for 0.5 API:

```rust
struct QuoteOption<T>(Option<T>);

impl<T: ToTokens> ToTokens for QuoteOption<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        tokens.append_all(match self.0 {
            Some(ref t) => quote! { ::std::option::Option::Some(#t) },
            None => quote! { ::std::option::Option::None },
        });
    }
}
```

**Comment by gnzlbg** [comment]
I also ran into this, thank you @flying-sheep for the `QuoteOption`. It took me a bit to find this because this issue is closed, and the docs do not mention anything about this.

I find it weird that quote interpolates all other types (AFAICT) "correctly", but when I want to interpolate an `Option<u32>` then, and only then, "magically-different behavior" happens and the `quote_spanned!` macro docs don't call this out.

**Comment by dtolnay** [comment]
I really don't know what you mean by "as is".

- `Box<T>` does not get interpolated as `::std::boxed::Box::new(foo)`.
- `&T` does not get interpolated as `&foo`.
- `String` does not get interpolated as `::std::borrow::ToOwned::to_owned("foo")`.

I continue to have strong conviction that the current behavior is the right behavior for `Option` so I encourage everyone to get used to it.

**Comment by gnzlbg** [comment]
I did not notice those, and I did not suggest that the current behavior is wrong. The only thing I did complain about is that it is extremely hard to discover what the behavior is.

**Comment by dtolnay** [comment]
That's fair! I would be on board with adding a sentence or two to the "Interpolation" section under https://docs.rs/quote/0.6/quote/macro.quote.html to clarify that values get interpolated according to the piece of syntax that they conceptually represent, not a transcription of the syntax tree node. Maybe using `String` and `Ident` as examples -- `Ident` does not get interpolated as `::syn::Ident::new("x", ...)` but as `x`.
