### ISSUE TITLE
quote!{} including other macros

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/quote#21]
A question by email:

> I want to include macro definitions and invocations in a quote!ed block (e.g. quote! { macro_rules! ... }). Doing this naively results in horrible name conflicts, as rust expands the macros on the spot.
>
> Is there a way to include macros inside a quote!{} that are NOT expanded within the block?

**Comment by dtolnay** [comment]
As you noticed, the input to `quote!` cannot contain dollar signs because of limitations of macro_rules. But dollar signs can come from interpolations! So this is one workaround:

```rust
#[macro_use]
extern crate quote;

fn main() {
    let dollar = quote::Ident::new("$");
    let tt = quote::Ident::new("$tt");

    println!("{}", quote! {
        macro_rules! id {
            (#dollar(#tt:tt)*) => {
                #dollar(#tt)*
            }
        }
    });
}
```

**Comment by rushmorem** [comment]
Very useful to know. Thanks!

**Comment by csharad** [comment]
This method no longer works, `Ident` provided by `syn` denies `$` being a valid ident. 
How to quote! a macro currently?
