### ISSUE TITLE
Why #var instead of $var?

### ISSUE THREAD

**Issue by withoutboats** [dtolnay/quote#22]
I was wondering why quote uses `#var` interpolation syntax instead of `$var`. My guess is that this is a limitation of the macro_rules system and not an intentional design decision. Is that correct? Is this a limitation that could be revisited in macros 2.0?

**Comment by dtolnay** [comment]
It is a limitation of macro_rules and could be revisited in macros 2.0. See the three comments starting at https://github.com/rust-lang/rust/issues/35900#issuecomment-252455427.

**Comment by withoutboats** [comment]
Thanks for the answer. I think we want to revisit how matching happens in 2.0 in general, its currently got a lot of limitations that could probably be rebalanced based on our experience with macro_rules.
