### ISSUE TITLE
Using `quote_spanned` can make proc-macro much less readable

### ISSUE THREAD

**Issue by Aaron1011** [dtolnay/quote#228]
I was recently writing a proc-macro to generate a wrapper function, which performs some conversions and calls a user-defined function. The relevant part of the macro looks something like this:

```rust
quote! {
    fn #name(this: SomeType, args: &[ArgType]) -> Result {
        #function_definition_tokenstream

        let this = {
            if let Some(val) = MyConversionTrait::convert(this) {
                val
            } else {
                return Err(some_error_creation());
            }
        };

        // Other argument-related code

        original_function(this, #(#arg_names),*); 
}
```

The code around `MyConversionTrait` gets types inferred based on the parameter types of `original_function`. If a compilation error occurs in that section of the function, it should be blamed on the parameter type written by the user. I refactored the code to look something like this:

```rust

let this_conversion = quote_spanned!{my_desired_span=> {
        let this = {
            if let Some(val) = MyConversionTrait::convert(this) {
                val
            } else {
                return Err(some_error_creation());
            }
        };
}

quote! {
    fn #name(this: SomeType, args: &[ArgType]) -> Result {
        #function_definition_tokenstream

        #do_this_conversion

        // Other argument-related code

        original_function(this, #(#arg_names),*); 
}
```

This achieves the desired result, but I find this kind of code to be *significantly* less readable, especially when I need to extract many different sections into distinct `quote_spanned!` blocks. I now need to read back-and-forth across the file to understand what the `quote!` block is doing, and it can be easy to lose track of exactly which bindings are introduced from which `TokenStream`. If not for the need to use `quote_spanned!`, I would have been able to use a single `quote!` call.

I'm not really sure how to solve this without introducing a lot of extra complexity into the `quote` crate - however, I wanted to raise the issue to see if anyone else had a similar view.

**Comment by dtolnay** [comment]
Thanks for the report. I think the way this is done currently is fine, but I would be interested if anyone wanted to experiment with other approaches in a different crate.
