### ISSUE TITLE
How to construct syntax::TokenStream from quote::Tokens?

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/quote#23]
It seems that I can construct proc_macro::TokenStream from quote::Tokens by just calling parse, but I cannot figure out how to construct a syntax::TokenStream from quote::Tokens. 

What is the typical way to do it?

**Comment by dtolnay** [comment]
I haven't tried this yet but this might work based on digging through libsyntax:

- `quote!(...)` gives you back a `quote::Tokens`
- `quote::Tokens` implements Display, call `to_string` to get a String
- parse the String into a `Vec<tokenstream::TokenTree>` using parse_tts_from_source_str (in libsyntax/parse/mod.rs)
- turn the `Vec<TokenTree>` into `tokenstream::Delimited` by using `token::DelimToken::NoDelim` as the delimiter
- turn the `Delimited` into a `syntax::TokenTree::Delimited`
- use the `impl From<TokenTree> for TokenStream`
