### ISSUE TITLE
Allow any `impl Spanned` for `quote_spanned!`

### ISSUE THREAD

**Issue by Kyuuhachi** [dtolnay/quote#231]
In almost all cases I find myself using the span of an existing AST node, so needing to write `.span()=>` everywhere is a lot of visual noise. And since `Span` is `impl Spanned`, I believe this would be backward compatible (though there could very well be some sort of special case I have not thought of). Would this be a reasonable change, or is there some reason it is not so?

**Comment by dtolnay** [comment]
I think this is all right as currently implemented, with `.span()=>` required if the desired span is the span of an AST node.

In my own macros I prefer avoiding `Spanned`, so adding a new implicit application of it would be counterproductive.
