### ISSUE TITLE
Iteration triggers `clippy::shadow_reuse`

### ISSUE THREAD

**Issue by c410-f3r** [dtolnay/quote#232]
```rust
#![deny(clippy::shadow_reuse)]

fn main() {
    let array = [1, 2, 3];
    let _ = quote::quote!(#(#array)*);
}
```

As seen above, the internal `quote!` implementation triggers `clippy::shadow_reuse` in downstream projects. To avoid such behaviour, please consider tweaking the codebase or `#[allow(clippy::shadow_reuse)]` where applicable.

**Comment by dtolnay** [comment]
I would prefer if this were fixed in clippy. As a `restriction` lint this shouldn't be triggering in macro-generated code unless quote itself opted into the restriction.
