### ISSUE TITLE
Array indexes ?

### ISSUE THREAD

**Issue by alkeryn** [dtolnay/quote#233]
would it be possible to access array indexes ?
if i want to do something like that for example :
```rust
 for i in 0..#first.len() {
     vec.push(format!(#fmt,#ast[i]));
 }
```
also ast's defined like this :
```rust
let parser = Punctuated::<syn::Expr, syn::Token![,]>::parse_separated_nonempty;
let ast = parser.parse(input).unwrap();
```
within a quote, as of right now, it doesn't do the desired behavior.
any idea ?

also calling fuctions like #ast.len(), wouldn't give the lenght for each expression if they are strings for example, but it'll give each expression, then the lenght of the last one.

**Comment by dtolnay** [comment]
I would prefer not to support this proposal in this crate.

**Comment by alkeryn** [comment]
Hey, i'm fine with this, however how would you go about doing it at all then ?
do you have an idea how you would manually do it ?
