### ISSUE TITLE
How to convert identifier into literal string?

### ISSUE THREAD

**Issue by knight42** [dtolnay/quote#24]
I want to use the same string of identifier in `#[cfg(feature = "...")]`. e.g. I try to generate some mods from the following enum:

```
#[derive(foo)]
enum Tests {
    a,
    b
}
```

to

```
#[cfg(feature = "a")]
mod test_a;
#[cfg(feature = "b")]
mod test_b;
```

**Comment by knight42** [comment]
Resolved.

**Comment by WesleyAC** [comment]
For anyone else who comes here from google — you can do this by doing `let foo = format!("{}", ident)` outside of the `quote!` invocation, and then using `#foo` inside of it as the string literal.

**Comment by akiradeveloper** [comment]
> inside of it

Sorry. What does this "it" mean?  Do you mean double quotes?
