### ISSUE TITLE
Recent update has a breaking change

### ISSUE THREAD

**Issue by ShayBox** [dtolnay/quote#241]
It appears a recent patch update has made breaking changes, causing `diesel` errors https://github.com/diesel-rs/diesel/issues/3541

**Comment by dtolnay** [comment]
I think this change was all right, since that trait Diesel is using has never been a public API.

**Comment by ShayBox** [comment]
I don't know much about the API and that's your decision, but in my opinion if the API wasn't meant to be public and/or usable then it shouldn't have been accessible.  

You should assume things are or will be used if accessible, even if you didn't intend it, and making a breaking change to one of the most used libraries can break other large projects.

**Comment by dtolnay** [comment]
The public API is documented here: https://docs.rs/quote/1. If something is not there, then it is not a public API.
