### ISSUE TITLE
Document implementation breaking footnotes in rustdocs

### ISSUE THREAD

**Issue by frehberg** [dtolnay/quote#248]
working with a macro generating rustdoc, it is using macro `quote!{ #[doc= ...])` to produce the corresponding tokenstream. 

Looking at the result using "cargo expand" the generated block is added to rustdoc as block comment using "/** ....*/",  the following is a minimalistic example, the quoted doc-fragment using block-quote instead of surrounding line-quotes:
```
/// This is a comment.
///
/// This is a diagram[^1]:
/**
 <script> const x = 1;</script>
*/
/// [^1]: This is a footnote.
pub fn example_with_footnote() {}
``` 

This is causing a switch between line-comment style and block-comment-style. The  footnote feature is loosing the context  and footnote references are not placed correctly.
![image](https://user-images.githubusercontent.com/4435830/225179565-3eadcbb4-140a-44b3-aadc-4be2c2e2c67f.png)

Instead of 
![image](https://user-images.githubusercontent.com/4435830/225179631-ccfc05c6-a603-4965-8bce-62229c2ca3c4.png)

Is there a way to tell quote!{ #[doc=..] } to produce line-comments?

**Comment by dtolnay** [comment]
I was not able to reproduce this based on that description.

**Comment by frehberg** [comment]
Many thanks for your time, I am a bit puzzled, you are right, the minimalized example does not show the issue with the block-comment (manually added),  but still I can reproduce the issuel with the proc-macro "aquamarine::aquamarine" using quote!

I am not sure now, it might be a rustdoc issue, maybe you can tell me.

I set up a demonstrator, please execute the following two steps:

git clone https://github.com/frehberg/aquamarine-demo.git; cd aquamarine-demo/; cargo doc

firefox ./target/doc/aquamarine_demo_crate/fn.example_fail_with_aquamarine.html

The browser will show this, the footnote at bottom should not be empty

![Screenshot from 2023-03-15 15-01-21](https://user-images.githubusercontent.com/4435830/225333377-da925ed9-7a48-4261-a82c-d08a0fef02f1.png)

**Comment by dtolnay** [comment]
Quote is behaving correctly as far as I can tell. That `#[aquamarine::aquamarine]` must be doing something incorrect.
