### ISSUE TITLE
How to escape `#` character to allow quoting a quote! { } block

### ISSUE THREAD

**Issue by sam0x17** [dtolnay/quote#249]
I am dynamically generating some proc macros and am in a situation where I need to write a `quote!` block that contains another `quote!` block including interpolations on the inner `quote!` block. I would like to escape the `#` somehow within the inner `quote!` block so that the outer/real `quote!` block does not interpret them as interpolations. Is this possible?

```rust
quote! {
    // ...
    quote! {
        // I need to escape these interpolations so they are copied verbatim
        // and ignored by the outer `quote!` block
        let #some_ident = #some_value;
    }
    // ...
}
```

**Comment by dtolnay** [comment]
See #142.
