### ISSUE TITLE
How do I use quote in a build script?

### ISSUE THREAD

**Issue by rushmorem** [dtolnay/quote#25]
I'm generating Rust code from a build script. However, when I call `as_str` or `to_string` on the generated `quote::Tokens` the resulting output has comments stripped out and the code is very hard to read. So my question is how do I get back human readable Rust code with comments from `quote::Tokens`?

For example, if I create a function like this:-
```rust
let hello = quote! {
    // Returns a string saying "Hello world!"
    fn hello_world() -> String {
        "Hello world!".into()
    }
};
```

Printing `hello.to_string()` displays:-
```rust
fn hello_world ( ) -> String { "Hello world!" . into ( ) }
```

I would like to get something like this instead:-
```rust
// Returns a string saying "Hello world!"
fn hello_world() -> String {
    "Hello world!".into()
}
```

/cc @dtolnay

**Comment by dtolnay** [comment]
You should use strings. This isn't something that macros in Rust can do at the moment.

The best options are plain old `format!` or [`unindent`](https://github.com/dtolnay/indoc#unindent).

```rust
let hello = unindent(r#"
      // Returns a string saying "Hello world!"
      fn hello_world() -> String {
          "Hello world!".into()
      }
      "#);
```

**Comment by rushmorem** [comment]
OK, thanks!

**Comment by gilescope** [comment]
Is this still the case?
