### ISSUE TITLE
Export struct from quote!

### ISSUE THREAD

**Issue by Massimiliano-solutiontech** [dtolnay/quote#256]
Maybe that's a noob question but I can't export a struct created inside a `quote!`
My goal is to use `MyStruct` outside the crate where the derive is created

```rust
let struct_token = quote! {
    pub struct MyStruct {
        pub id: u32,
        pub val: String,
    }
};

let tokens = quote! {
    ...
    #struct_token
    ...
};

TokenStream::from(tokens)
```

**Comment by dtolnay** [comment]
Hi @Massimiliano-solutiontech, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community.
