### ISSUE TITLE
How to pass the result of `quote!` to prettyplease? 

### ISSUE THREAD

**Issue by sztomi** [dtolnay/quote#258]
The documentation says 

<blockquote>
When using quote in a build.rs or main.rs and writing the output out to a file, consider having the code generator pass the tokens through [prettyplease](https://github.com/dtolnay/prettyplease) before writing.
</blockquote>

but how? The result of `quote!` is a `TokenStream`, but prettyplease expects a `syn::File`. Is there a straightforward & efficient conversion?

**Comment by dtolnay** [comment]
https://docs.rs/syn/2/syn/fn.parse_file.html

**Comment by dtolnay** [comment]
Er, this one: https://docs.rs/syn/2/syn/fn.parse2.html
