### ISSUE TITLE
How to insert a hex literal into a TokenStream?

### ISSUE THREAD

**Issue by xpe** [dtolnay/quote#263]
I would like to insert a hex literal into a TokenStream. I don't see any way to do this. Did I overlook some way(s)?

My use case: I want to generate code containing hex literal bitmasks: these read much better as `0xFFFF` than `65535`.

If there is no such functionality nor workarounds, would you be open to a PR?

P.S. Thanks for such an impressive set of libraries!

**Comment by dtolnay** [comment]
```rust
let literal = format!("{:#x}", int).parse::<proc_macro2::Literal>().unwrap()
quote!(#literal)
```
