### ISSUE TITLE
ToTokens for NonZero integers?

### ISSUE THREAD

**Issue by greyblake** [dtolnay/quote#268]
Hi,
thank you for the crate and  your work, which powers a lot of library developers :heart: 
________

## Request

Is there any chance to implement `ToTokens` for NonZero integers? (`::core::num::NonZeroU8`, etc...)

If you're fine with the idea, I could open a PR.
It may not be a plane decision, how NonZero integer should be converted into tokens

##### Variant A (with a runtime penalty):
```rs
::core::num::NonZeroU8::new(123).unwrap()
```
##### Variant B (with unsafe):
```rs
unsafe { ::core::num::NonZeroU8::new_unchecked(123) }
```

## Context

In [nutype](https://github.com/greyblake/nutype) I'd like to add support for NonZero integers. With my current implementation the effort would be relatively low if NonZero integers implemented `ToTokens`?

**Comment by dtolnay** [comment]
I think I would prefer not to build this into this crate. Hopefully there's a different way you could handle these in nutype.

**Comment by greyblake** [comment]
@dtolnay All cool. Thanks for the quick reply.
