### ISSUE TITLE
Add special syntax for using strings as identifiers

### ISSUE THREAD

**Issue by nyurik** [dtolnay/quote#284]
Far too often I find myself having a `String` with the needed identifier:

```rust
fn construct_foo_call(type_name: &str) -> TokenStream {
    let ident = format_ident!("{type_name}");
    quote! {
        foo(#ident);
    }
}
```

Is there a way `quote!` can support direct usage of strings as identifiers, e.g.

```rust
fn construct_foo_call(type_name: &str) -> TokenStream {
    quote! {
        foo(##type_name);
    }
}
```

or

```rust
fn construct_foo_call(type_name: &str) -> TokenStream {
    quote! {
        foo(@type_name);
    }
}
```

**Comment by dtolnay** [comment]
I would prefer not to add new special syntax in this crate for this operation. But, you're free to make your own quasiquoting macro crate that is more fully featured.
