### ISSUE TITLE
Feature Request : Option Expansion

### ISSUE THREAD

**Issue by NovaliX-Dev** [dtolnay/quote#285]
_This issue is kinda similar to #20, but it propose something more featured and more general._

The macros in rust have a syntax for tokens with zero or one ocurences : 
`$(<something>)?`.

I would like to have this implemented for the quote macro as well, and one of the possible application for this syntax is for the optioned tokens.

Here is an example (assembled in like 5 minutes) of how i'm seeing things : 
- Case where the option contains indeed something 
```rust
let var = Some(quote!{ something })
quote!(bla #(_ => #var)? bla) // will output bla _ => something bla
```
- Case where the option contains nothing
```rust
let var: Option<TokenStream> = None
quote!(bla #(_ => #var)? bla) // will output bla bla
```

For the moment I'm implementing this in the manual way, by storing the conditionally produced tokens an intermediate variable and then using that variable in a final quote macro:
```rust
let var = Some(quote!{ something })

// ...

let default_tokens = match var {
    Some(val) => quote! { _ => #val },
    None => TokenStream::new()
};

// ...

quote! { bla #default_tokens bla }
```

What do you all think about this proposal ?

**Comment by dtolnay** [comment]
This is already supported well enough by interpolating iterators.

```rust
let val = option.iter();
quote!(bla #(_ => #val)* bla)
```

**Comment by NovaliX-Dev** [comment]
Thank you for you're quick response ! But the problem still remains : we create a temp variable, something i was trying to avoid.
