### ISSUE TITLE
Trait `quote::ToTokens` is not implemented for `serde_json::Value`

### ISSUE THREAD

**Issue by glennpierce** [dtolnay/quote#33]
This is probably an unusual question and there maybe a better way but thought I would ask.

I have implemented a custom derive to implement an interface. One of the methods I implement
returns the fields as json. Each field returned has a name, type and doc string in the source.

so something like

```
 let type_json = json!({
        "name": name.to_string(),
        "type": type.to_string(),
        "doc": doc.to_string(),
        });

```

However, I cant return with quote like

```
quote! {
        impl #impl_generics ElementProperties for #name #ty_generics #where_clause {
            fn type_description(&self) -> serde_json::Value {
                #type_json
            }
        }
    }

```

as I get the error

the trait `quote::ToTokens` is not implemented for `serde_json::Value`

If I try to return as strings I get double escaping.

Is there some way I can return json or a json string without escaped values from a method ?

thanks

**Comment by dtolnay** [comment]
Code that you want to run in the user's crate needs to be inside of `quote!`, including code that builds JSON objects. Maybe something like this:

```rust
quote! {
    impl #impl_generics ElementProperties for #name #ty_generics #where_clause {
        fn type_description(&self) -> ::serde_json::Value {
            let mut map = ::serde_json::Map::new();
            map.insert("name".to_owned(), ::serde_json::Value::String(#name.to_owned()));
            map.insert("type".to_owned(), ::serde_json::Value::String(#typ.to_owned()));
            map.insert("doc".to_owned(), ::serde_json::Value::String(#doc.to_owned()));
            ::serde_json::Value::Object(map)
        }
    }
}
```

**Comment by glennpierce** [comment]
Ok so I found your answer to another question that works here.

#![recursion_limit = "128"]
