### ISSUE TITLE
Interpolate ident into string?

### ISSUE THREAD

**Issue by chengyuhui** [dtolnay/quote#35]
I have to do something like
```rust
quote! { args.push_str("#ident"); }
```
How can I do this?

**Comment by chengyuhui** [comment]
I came across `stringify!()` minutes after this issue... Is there any difference?

**Comment by dtolnay** [comment]
Yes there is a difference. Stringify is less flexible and will not always work. For example in the following you would not be able to use stringify:

```rust
macro_rules! m {
    ($n:tt) => {
        println!("name: {}", $n);
    }
}

fn main() {
    m!("chengyuhui");

    // not allowed
    m!(stringify!(chengyuhui));
}
```

**Comment by clarcharr** [comment]
@dtolnay wouldn't `ident.as_ref()` be more efficient?

**Comment by dtolnay** [comment]
Yes in theory, but macro performance is never worth worrying about. The entire macro expansion process takes a fraction of a percent of total compile time and does a large number of allocations. In my opinion `to_string()` more clearly conveys that we take something that is not a string and represent it as a string, but `as_ref()` would work here too.

**Comment by mystor** [comment]
I think we can close this, as @dtolnay has pointed out the solution to this problem :).
