### ISSUE TITLE
Special-case more tokens in `quote_each_token`

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/quote#38]
Right now there's a final [catch-all](https://github.com/dtolnay/quote/blob/master/src/lib.rs#L271-L275) which stringifies all tokens and re-parses them at runtime.

This probably isn't the speediest thing and we should catch things like keywords and symbols if we can (esp identifers). I think the catch-all will likely need to always stay, but we can at least optimize common use cases! An example of a token we can't catch I believe is a lifetime.

**Comment by dtolnay** [comment]
Fixed in #77.
