### ISSUE TITLE
Quoting Traits in quote?

### ISSUE THREAD

**Issue by Ygg01** [dtolnay/quote#41]
Is there any guide how to quote traits in [`quote`](https://doc.rust-lang.org/1.5.0/book/macros.html#the-variable-crate) in order to ensure they'll be in scope. A kind of `$crate` for procedural macros?

For example I want to ensure `SomeTrait` is always in scope?
```
quote!(
     struct Foo {
        bar: [SomeTrait;#len]
     }
)
```

https://stackoverflow.com/questions/44950574/using-crate-in-rusts-procedural-macros

**Comment by alexcrichton** [comment]
Unfortunately I don't think there's a way to do this right now. In theory with "proper hygiene" this'll be possible but I don't think we're quite there yet.

**Comment by Ygg01** [comment]
@alexcrichton hmm, what are best practices in that case? `::origin_crate::SomeTrait`?

**Comment by alexcrichton** [comment]
If you can it's best to inject the `extern crate` yourself to unambiguously reference it, but that's unfortunately not possible in all circumstances. In those cases then yeah, just using global paths is the best we've got :(
