### ISSUE TITLE
How to quote type arguments

### ISSUE THREAD

**Issue by bruceg** [dtolnay/quote#44]
I am writing a derive macro. In my code, I have extracted a generic type (say Option<String>) from the struct into an Ty. I want to write something like the following:

`quote! { let #name = #ty::default(); }`

However, for generic types, Rust wants an extra `::` between the parts, and this doesn't work. That is, it requires `Option::<String>::default()` instead of `Option<String>::default()`. The error message is:

> help: use `::<...>` instead of `<...>` if you meant to specify type arguments

How can I accomplish this? Am I doing something wrong?

(for the Option case in particular, I could just initialize it to `None`, but I also needs to call a completely different trait function later as well)

**Comment by dtolnay** [comment]
`<#ty>::default()` or `<#ty as Default>::default()`.

**Comment by bruceg** [comment]
Ok, that's very simple. Thanks.
