### ISSUE TITLE
Consider representing tokens with a rope-like structure internally

### ISSUE THREAD

**Issue by fitzgen** [dtolnay/quote#45]
This would allow for `O(1)` concatenation and prepending, which seems like what most interpolations / building up trees of tokens is doing.

(No, I don't have any benchmarks or profiles yet, just a suspicion and felt like this issue was worth opening for investigation / discussion)

**Comment by dtolnay** [comment]
Thanks, I agree we should experiment with this. In particular, let's make sure to avoid adding anything silly like `AsRef<[TokenTree]> for Tokens`.

**Comment by mystor** [comment]
I think this is generally a good idea, and we definitely shouldn't commit to a vector based implementation in the public API.

**Comment by dtolnay** [comment]
Long term the relevant place to implement this optimization would be the TokenStream type in the compiler's libproc_macro. As that stuff approaches stabilization we will do a round of benchmarking and optimization. Thanks for the idea!
