### ISSUE TITLE
Publish 0.4?

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/quote#46]
@dtolnay what do you think about publishing 0.4 which depends on `proc-macro2 v0.1.*`?

I think the API concerns were mostly around `syn`, right?

**Comment by mystor** [comment]
It would be unfortunate & a bit confusing for people who want to use `syn` and `quote` (which are often depended on together) to have to pick a not-most-recent version of `quote` to be able to use the most recent version of `syn`. I'd be inclined to release the new versions in lockstep.

**Comment by alexcrichton** [comment]
Ah right yes, makes sense!
