### ISSUE TITLE
Implement FromIterator<Tokens> for Tokens?

### ISSUE THREAD

**Issue by pnkfelix** [dtolnay/quote#48]
Caveat: I'm totally unaware of what "best practices" are when it comes to the `quote` crate. I'm just trying to make some little demos.

I have found myself building up blocks of code by repeatedly doing:

```rust
let mut code = quote! { }
loop {
  let new_stuff = ...;
  code = quote! { #code #new_stuff }
}
```

But when I already have an iterator in hand (or am mapping over one to convert the input into tokens accordingly),  it seems like it might be nice to be able to do:

```rust
let code: quote::Tokens = args.iter()
    .map(|a| transform(a))
    .map(|transformed| quote! { #transformed })
    .collect();
```

Unfortunately the latter does not work; you get the error:

```
error[E0277]: the trait bound `quote::Tokens: std::iter::FromIterator<quote::Tokens>` is not satisfied
```

**Comment by mystor** [comment]
I think that having a FromIterator implementation wouldn't be a bad idea, but we already do have a mechanism for doing things like this. I believe the following should work:

```rust
let code = args.iter().map(|a| transform(a));
let result = quote!(#(#code)*);
```

Which will consume the iterator of `ToTokens` objects and concatenate them all into a single `Tokens` object.

**Comment by dtolnay** [comment]
I would prefer to double down on `#(#iter)*` repetitions. Many times when joining tokens you want a separator between each one or a terminator after each one, and you get those things quite naturally with a repetition and not with FromIterator. I think for now we get more benefit from consistently reaching for a repetition than we would get from adding support for FromIterator / collect.
