### ISSUE TITLE
Implement `Debug` for `Tokens`

### ISSUE THREAD

**Issue by mystor** [dtolnay/quote#49]
Right now you can't `#[derive(Debug)]` on a type containing a `Tokens`, which is kinda inconvenient.

**Comment by colin-kiegel** [comment]
It would probably increase compile times, but I would also consider `Debug` for public types a good practice :-)

**Comment by mystor** [comment]
We already implement `Display` for `Tokens` - implementing `Debug` as just forwarding to `Display` (perhaps with a `Tokens(...)` around it?) would probably work fine, and I can't imagine it would hurt compile times noticeably.
