### ISSUE TITLE
Buggy repetition or repetition docs

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/quote#53]
The readme says:

```quote
Repetition is done using #(...)* or #(...),* very similar to macro_rules!:

#(#var)* - no separators
#(#var),* - the character before the asterisk is used as a separator
#( struct #var; )* - the repetition can contain other things
#( #k => println!("{}", #v), )* - even multiple interpolations
```

which suggests that:

```rust
let a  = vec![0, 1, 2, 3]; 
let q = quote! { #(#a)&&+ };
println!("{:?}, q);
```

will expand to `0 && 1 && 2 && 3`, but this is not true. In particular `&&` is not used as the repetition separator.

Also: 

```
let q = quote! { #(#a)+ };
```
without any separator does introduce `,` as separators. 

---

I also don't think that [the 100 lines of completely undocumented code in the DeepClone crate](https://github.com/asajeffrey/deep-clone/blob/master/deep-clone-derive/lib.rs) are a good hint for beginners trying to understand this crate.

**Comment by dtolnay** [comment]
The readme says to use `*`. This should work: `quote! { #(#a)&&* }`.

**Comment by gnzlbg** [comment]
Isn't `*` zero or more while `+` is one or more ?

**Comment by dtolnay** [comment]
¯\\_(ツ)_/¯ we only support `*`. If you want the code to panic when there are no elements, you need to write the panic yourself. This is good because generally the programmer will be able to produce a much more helpful message than the library could.

```rust
if a.is_empty() {
    panic!("At least one #[conjunction = N] attribute is required");
}
let q = quote! { #(#a)&&* };
```

**Comment by gnzlbg** [comment]
> ¯\(ツ)/¯ we only support *.

I see, I did not know that. I was trying only with `+` and the experience was very frustrating. I completely missed that info when looking at the readme.
