### ISSUE TITLE
Remove ToTokens for vec, slice, arrays

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/quote#54]
These make it too easy to write code that compiles but does not do what you wanted, when you meant to write a repetition. Users should write out the repetition themselves.

```rust
quote! { [ #(#vec,)* ] }
```

**Comment by alexcrichton** [comment]
👍 

This has bitten me quite a few times!

**Comment by mystor** [comment]
👍 this has also bitten me, very good change.

**Comment by iirelu** [comment]
Wait, why was this removed? How do you, say, do `const THING: &[u8] = #vec_thing` inside a `quote!` macro now?

**Comment by dtolnay** [comment]
@iirelu it would be similar to what is shown above, using a repetition:

```rust
quote! {
    const THING: &[u8] = &[ #(#vec_thing),* ];
}
```

**Comment by iirelu** [comment]
Oh, seriously? That's a lot more convenient than the huge function I ended up making for it. Thanks!

**Comment by BGluth** [comment]
I understand the motive for this and think it's a good idea, but I don't understand why ToTokens for tuples was removed as well.

For example, previously if I had an iterator of tuples I could do this:
```Rust
#(
    let (thing_1, thing_2) = #some_iter_of_tuples;
    ...
)*
```

I think this may be a pretty rare and unusual use case however (I'm generating functions that output data computed at compile time).

The only two other alternative options that I can think of now are to either:
- Use separate iterators for each item in the tuple
- Create a struct and manually implement to tokens for it

**Comment by dtolnay** [comment]
@BGluth something like this could work:

```rust
let things = some_iter_of_tuples.map(|(t1, t2)| quote! { (#t1, #t2) });

quote! {
    #(
        let (thing_1, thing_2) = #things;
        ...
    )*
}
```

**Comment by BGluth** [comment]
Really is that it? That's awesome thanks!
