### ISSUE TITLE
Ability to disable runtime dependency on rustc toolchain libs

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/quote#63]
As explained in #62, unconditionally referring to `extern crate proc_macro` is problematic. In the next round of breaking changes we will need to put that dependency behind a flag.

**Comment by staktrace** [comment]
@dtolnay Do you have an ETA on this? More and more crates are starting to pick up the version of quote/syn that use proc-macro2 and so the infestation of things needing proc_macro is increasing. For example the latest version of `serde_derive` just published picks it up as well and so now anything that tries to do a `cargo install` of any binary that uses serde_derive 1.0.* will fail to run (I think).

**Comment by staktrace** [comment]
Actually the above might not be totally correct. Still investigating, but it would be good to get an ETA on when you are planning to making the breaking change.

**Comment by Eijebong** [comment]
Am interested in an ETA too as this is blocking the deduplication of quote in servo because of bindgen dependency ;)

**Comment by dtolnay** [comment]
Reopened and merged #62.
