### ISSUE TITLE
How to interpolate String as ident

### ISSUE THREAD

**Issue by dignati** [dtolnay/quote#67]
Hey, I hope this is the right place to ask:

I need to interpolate a string as an ident (so without quotation marks). Is there some easy way to do this?

**Comment by dtolnay** [comment]
You would construct a [`syn::Ident`](https://docs.rs/syn/0.12/syn/struct.Ident.html) from the string and interpolate that -- the link shows an example. If you are not already using Syn you can do the same thing through the lower level [`proc_macro2::Term`](https://docs.rs/proc-macro2/0.2/proc_macro2/struct.Term.html) which can also be interpolated.

**Comment by dignati** [comment]
Perfect, thank you! :)
