### ISSUE TITLE
Building Tokens incrementally with quote 0.5

### ISSUE THREAD

**Issue by jimmycuadra** [dtolnay/quote#72]
I'm working on updating [ruma-api-macros](https://github.com/ruma/ruma-api-macros) from syn 0.11 to 0.13 and from quote 0.3 to 0.5 and the API for appending tokens to a `Tokens` has changed in a way that is confusing. I'd like to see if I'm approaching this the right way or if there's a cleaner way.

Before I had code like this:

``` rust
let mut tokens = Tokens::new();
# ...
tokens.append(quote! {
    # ...
});
tokens.append("(");
tokens.append(quote! {
    # ...
});
tokens.append(")");
```

With quote 0.5, all these calls fail with errors like these:

```
the trait bound `quote::__rt::TokenTree: std::convert::From<quote::Tokens>` is not satisfied
```

```
the trait bound `quote::__rt::TokenTree: std::convert::From<&str>` is not satisfied
```

This seems to be because `Tokens::append`'s argument is now `T: Into<TokenTree>` rather than `T: ToTokens`. The `append_all` method _does_ accept `Tokens`, which means when appending the output of a quote macro I can just change to `append_all`:

``` rust
tokens.append_all(quote! {
    # ...
});
```

Annoying, but okay. Appending a string slice directly doesn't work with `append_all` because it can't be converted into an iterator implicitly. But I can do something like:

``` rust
tokens.append_all("(".chars());
```

That will work, but it seems pretty indirect. Is there a better way of doing this? It may be something obvious I'm missing, but in either case it'd be helpful to have some documentation that explains this better.

Thanks much!

**Comment by dtolnay** [comment]
Similarly to how it's always worked in macro_rules macros, now the token representation in procedural macros no longer has a representation for mismatched delimiters. That means `(` is not a representable token stream and there is no equivalent to `tokens.append("(")`.

Generally `&mut Tokens` should be a pretty unusual occurrence in a procedural macro -- including calls to `append` and `append_all`. In serde_derive we don't use a single call to either of those. The generated tokens should be built using `quote!` instead:

```rust
quote! {
    // ...
    (
        // ...
    )
}
```

The closest you could get to `tokens.append("(")` would be by dropping down to the level of proc-macro tokens and [`Group`](https://doc.rust-lang.org/nightly/proc_macro/struct.Group.html), but it still will require balanced delimiters.

```rust
use proc_macro2::{Group, Delimiter};

tokens.append(Group::new(Delimiter::Parenthesis, content));
```
