### ISSUE TITLE
Cannot use outside of procedural macro

### ISSUE THREAD

**Issue by gmorenz** [dtolnay/quote#79]
The readme says

> This crate is motivated by the procedural macro use case, but is a general-purpose Rust quasi-quoting library and is not specific to procedural macros.

If I try to use it outside of a procedural macro, e.g.

```rust
#[macro_use]
extern crate quote

fn main() {
    let x = quote!{};
}
```

I get the following error

```
thread 'main' panicked at 'procedural macro API is used outside of a procedural macro', libproc_macro/lib.rs:1294:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by dtolnay** [comment]
For now, it should be working anyway despite the message that gets printed. https://github.com/alexcrichton/proc-macro2/issues/122 is tracking getting rid of the message.

**Comment by gmorenz** [comment]
Oh, you're right, it is. I saw that error and just assumed that the program terminated immediately.

Feel free to close this (or not if you want to track this here as well).

**Comment by dtolnay** [comment]
Fixed in https://github.com/alexcrichton/proc-macro2/pull/123.
