### ISSUE TITLE
When using the `quote` crate why I need the `proc_macro2` crate even when I am on nightly ?

### ISSUE THREAD

**Issue by xieyuheng** [dtolnay/quote#81]

**Comment by dtolnay** [comment]
The libproc_macro data structures are not consistently available on nightly. You can compile code against it, but if used from a build.rs or binary crate every function call will panic. The proc_macro2 crate makes the same API available consistently across use cases.

**Comment by xieyuheng** [comment]
Thank you Sir.

Will this :: https://doc.rust-lang.org/proc_macro/fn.quote.html
be compatible with the `quote` crate in the future ?

**Comment by dtolnay** [comment]
I don't know what the plan is for that macro. It is not actively being worked on. The input syntax is different from the macro in this crate.
