### ISSUE TITLE
Re-implement as a procedural macro

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/quote#82]
This would make it possible to support duplicate interpolations inside a repetition, #8.

**Comment by eddyb** [comment]
Would it also allow solving #10?

Then again, other than difficulties around nesting braces, I'd probably prefer imperative code (`for`, `if/else`, `match`, etc.) pushing smaller quoted fragments into a larger buffer, to some iterator adapter monstrosity. (generators would also help, I suppose)

**Comment by dtolnay** [comment]
I posted a request for implementation as a separate library: https://github.com/dtolnay/request-for-implementation/issues/8.

**Comment by mystor** [comment]
One problem with this is currently related to the limitations on procedural macros. At one point I had an initial implementation which took this approach. Unfortunately, procedural macros cannot currently generate code in expression or statement context, meaning that lots of workarounds are needed to generate the necessary code in a module generated by a declarative macro, which then has to be imported and invoked by the caller.

There are also issues around resolution of named functions and types. proc_macro currently has no support for a `$crate::` like prefix which would make lookups of specific traits & types easy.

Finally, there's no good way to accurately round-trip Literal tokens. `Literal` tokens can only be either:
1. Created with a given value, in which case their `to_string` representation may not match the original one, or
2. Parsed as a `TokenStream`, and then unwrapped at runtime.

**Comment by mystor** [comment]
I figured I'd post a branch with my super sketchy implementation which caused me to find some of these issues. I don't think it's ready to merge yet & it adds a lot of complexity, but perhaps it will be useful to whoever decides to try to implement this in the future.

https://github.com/mystor/quote/tree/proc_quote

**Comment by dtolnay** [comment]
Closing in favor of https://github.com/dtolnay/request-for-implementation/issues/8. I don't foresee a procedural macro reimplementation displacing the foundational role of quote, but it is possible that libraries where #8 comes up especially often for some reason will opt to use the procedural macro one.
