### ISSUE TITLE
Support pushing tokens to an existing `TokenStream`

### ISSUE THREAD

**Issue by dhardy** [dtolnay/quote#85]
Something like this:
```rust
#[macro_export(local_inner_macros)]
macro_rules! quote_push {
    ($stream:ident, $($tt:tt)*) => (quote_push_spanned!($stream, $crate::__rt::Span::call_site()=> $($tt)*));
}

#[macro_export(local_inner_macros)]
macro_rules! quote_push_spanned {
    ($stream:ident, $span:expr=> $($tt:tt)*) => {
        {
            let _span = $span;
            quote_each_token!($stream _span $($tt)*);
        }
    };
}
```

I'm currently having to use `toks.extend(once(quote! { ... }));`.

**Comment by hcpl** [comment]
[`toks.append_all(quote! { ... })`](https://docs.rs/quote/0.6.9/quote/trait.TokenStreamExt.html#tymethod.append_all)?

**Comment by dhardy** [comment]
Same thing isn't it?

What would be even better would be allowing embedding similar to `Debug::fmt` — i.e. making a macro like `quotable` return an object supporting `ToTokens`. Probably this could be done with a closure to allow lazy execution (i.e. add to a `TokenStream` only once); though it's not obvious if this would have any real benefit.

**Comment by dhardy** [comment]
Sorry, I see that's already possible — for some reason I missed `impl ToTokens for TokenStream`.

**Comment by CreepySkeleton** [comment]
The thing is: `toks.append_all(quote! { ... })` does involve an extra allocation while building the inner `quote!{}` invocation. `quote_push` is free from this disadvantage.
