### ISSUE TITLE
Quote is hard to use for non-procmacro code generation

### ISSUE THREAD

**Issue by jsgf** [dtolnay/quote#90]
I'm using `quote` for Thrift in a stand-alone code generator. With `quote` prior to 0.4 this worked pretty well, but in more recent versions it has become more tightly coupled with proc macros. I've been working around this, but it has become increasingly difficult. Since procmacros became stabilized, it means that my codegen binary now has a dynamic linkage with `libproc_macro-*.so` which is awkward for an otherwise statically-linked binary.

In the short term, it would be nice if there was also a static `libproc_macro` for this case, but I think a longer-term solution would be to either make it possible to compile `quote` independently from proc macros (which isn't really possible with the feature system), or some other crate with a similar API.

I'm not really sure what the practicalities of this are, but I think it would be important to make sure they share any code which depends on changes to the language so they both keep up to date as it evolves without doubling the effort.

**Comment by dtolnay** [comment]
I believe this is fixed as of https://github.com/rust-lang/rust/pull/49219. Could you try it with a 1.32 beta compiler or a recent nightly? You should see that there is no longer a dynamically linked dependency on libproc_macro.

**Comment by jsgf** [comment]
Great! I'll give it a go when I get the chance.

**Comment by dtolnay** [comment]
Closing again... As a Rust quasi-quoter, it seems essential that we produce output in the form of Rust tokens. The canonical definition of Rust tokens is what is provided by proc-macro.

Other designs are possible but I would prefer to see that explored in a different crate.

**Comment by jsgf** [comment]
So that suggests that the canonical token code should be refactored out of proc-macro to be usable elsewhere?

**Comment by dtolnay** [comment]
Yep! And that is [proc-macro2](https://github.com/alexcrichton/proc-macro2). It provides the proc-macro canonical token representation in way that is usable elsewhere. Technically quote is implemented against proc-macro2 and not proc-macro.
