### ISSUE TITLE
Not enough examples in documentation to understand what is possible with the crate.

### ISSUE THREAD

**Issue by SoftwareApe** [dtolnay/quote#92]
It's explained in many places how to use quote! with # on variables in your namespace. The docs don't seem to go into detail on anything else though. It would be very helpful to have examples on what you can and can't do with the crate.

**Comment by SoftwareApe** [comment]
One example that would be nice is how to combine multiple quotes. Everything above a basic derive macro will need multiple parts of code stitched together.

let quote1 = quote! {...};
let quote2 =quote! {...};

now if we want to return quote1 + quote2, how do we do that?

**Comment by SoftwareApe** [comment]
If we have a variable that is a string and we want to have it in the quote without quotes "...", how do we do that?

**Comment by SoftwareApe** [comment]
How do the repetitions look in more complicated cases.

**Comment by SoftwareApe** [comment]
Also in the current example, where do the variables with # come from. It would be nice to have some context.

**Comment by dtolnay** [comment]
Closing because the examples added in #93 should help understand how this library is intended to be used. Thanks!

The Syn examples (https://github.com/dtolnay/syn/tree/master/examples) show some more realistic usage in context, since that tends to require syntax trees.
