### ISSUE TITLE
More impl ToTokens examples

### ISSUE THREAD

**Issue by dginev** [dtolnay/quote#94]
My code is returning a struct, let's call it `Data` from within a Custom Derive sub-crate, and had to implement `quote::ToTokens` for `Data` to make that possible. As my struct was the newtype pattern over a `Vec<Datum>`, it would have been amazing to start from an example that did something similar with some other wrapped `Vec<T>`. 

I wanted to donate back the code I ended up with, which should at least illustrate the documentation gaps in my head:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=03acf37f5eeb1e5e156126a270dfafda

I still don't know if I implemented this in a "best practice" way, but I wanted to make an issue to suggest more examples with implementing ToTokens may be useful.

**Comment by dtolnay** [comment]
Thanks, that is helpful.

If I were writing this impl I would write it as:

```rust
use proc_macro2::TokenStream;
use quote::{quote, ToTokens};

struct Datum(u8);
struct Data(Vec<Datum>);

impl ToTokens for Data {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let d = self.0.iter().map(|datum| datum.0);
        tokens.extend(quote! {
            Data(<[Datum]>::into_vec(Box::new([ #( Datum(#d) ),* ])))
        })
    }
}

fn main() {
    let d = Data(vec![Datum(2), Datum(4), Datum(6)]);
    println!("{}", quote!(#d));
}
```

**Comment by dginev** [comment]
@dtolnay that's massively more elegant than the explicit approach, thanks! What I couldn't find out is how to use the `.extend` + `quote!()` combo when I want to delegate the inner tokenization entirely, such as: `datum.to_tokens(tokens)`. That's particularly important when you have a Vec over a complex struct, and it would be a big undertaking to write the inner tokenization.

**Comment by dtolnay** [comment]
Datum can be interpolated as a whole, much the same way:

```rust
impl ToTokens for Datum {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let n = self.0;
        tokens.extend(quote! {
            Datum(#n)
        });
    }
}

impl ToTokens for Data {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let d = &self.0;
        tokens.extend(quote! {
            Data(<[Datum]>::into_vec(Box::new([ #(#d),* ])))
        });
    }
}
```

**Comment by dginev** [comment]
Oh wow, this is exactly the missing piece I needed! A trivial refactor and I have my code running with tests passing. In retrospect I am a bit shocked I never tried this, somehow had a mental block about interpolating over a `&self.0` field -- didn't look like the type of object one would be interpolating over, but unsure why I assumed that? Thanks again!!
