### ISSUE TITLE
Using a spanned TokenStream inside quote! appears to lose span information

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/quote#95]
In the code below, `Field` is given a span and told to produce per-field initializers which are spanned back to the originally-declared fields the declaration is read from. I've confirmed that `Field`'s `span` property is being set correctly, and is not equal to `Span::call_site()` immediately prior to the `quote_spanned` invocation.

```rust
use std::borrow::Cow;

use darling::ast::Fields;
use proc_macro2::{Span, TokenStream};
use quote::ToTokens;
use syn::{Attribute, Ident, Path};

/// Receiver for trait impl; this gets the struct ident and the fields
/// in the struct.
pub struct TraitImpl<'a> {
    pub ident: &'a Ident,
    pub attrs: &'a [Attribute],
    pub fields: Fields<Field<'a>>,
}

impl<'a> TraitImpl<'a> {
    fn body(&self) -> TokenStream {
        if self.fields.style.is_struct() {
            let fields = self.fields.as_ref();
            quote! { Self { #(#fields),* }}
        } else {
            let ident = &self.ident;
            let fields = self.fields.as_ref();
            quote! { #ident(#(#fields),*) }
        }
    }
}

impl<'a> ToTokens for TraitImpl<'a> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let body = self.body();
        let ident = &self.ident;
        let attrs = self.attrs.iter();
        tokens.extend(quote! {
            #(#attrs)*
            impl ::std::default::Default for #ident {
                fn default() -> Self {
                    #body
                }
            }
        });
    }
}

pub struct Field<'a> {
    pub span: &'a Span,
    pub ident: Option<&'a Ident>,
    pub path: Cow<'a, Path>,
}

impl<'a> ToTokens for Field<'a> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let Field {
            ref span,
            ref ident,
            ref path,
        } = *self;

        let span = *span.clone();
        if let Some(ident) = ident {
            tokens.extend(quote_spanned!(span=> #ident: #path()));
        } else {
            tokens.extend(quote_spanned!(span=> #path()));
        }
    }
}
```

However, when I deliberately add a field to the input struct that should cause a failure, such as one of type `std::net::IpAddr`, the emitted compiler error points to `Span::call_site`. I think this is because `quote!` is overwriting the field-level span information I've provided.

Based on reading the docs about composing sections of generated code, I expected this to work. Is there a way to do this that preserves the readability of the block that shows the shape of the emitted code, or am I out of luck?

**Comment by dtolnay** [comment]
The span in quote_spanned only applies to tokens that originate within the quote_spanned invocation, so the `:` and `()` tokens in your case. Interpolated values keep their span. Is that the behavior you are expecting?

You can use `println!("{:#?}", tokens)` at various points to determine exactly where the spans go wrong. A call_site span would look like `span: #0 bytes(0..0)` in the debug output.

**Comment by TedDriggs** [comment]
Oh, my understanding was backward then. Is there a way to set the span of an already-constructed syn path, or do I need to thread that information all the way through to where the path is constructed?

**Comment by dtolnay** [comment]
You basically shouldn't ever need to rewrite the span of an existing parsed Path. I don't know of a use case where that would be the right behavior. How is this coming up?

**Comment by TedDriggs** [comment]
To avoid rewriting the same trait path in multiple places in my code, I have a helper function that returns the path. It was declared as `fn trait_path() -> Path`.

For now, I've rewritten it as `fn trait_path(span: Span) -> Path` and am using `quote_spanned!` to set the path. However, I then ran into a case where I needed to add a segment to the path, and I wanted that segment to have the same span. That led to creating a new ident with the span read off the `Path`, and then pushing that onto the `Path`. That worked, but it's pretty ugly to read.

**Comment by TedDriggs** [comment]
Here's one more use-case: I have this struct, `SpannedValue<T>`, which is supposed to represent a thing at a location.

```rust
#[derive(Debug, Clone)]
pub struct SpannedValue<T> {
    value: T,
    span: Span,
}
```

I'd like to add an impl like the following:

```rust
impl<T: ToTokens> ToTokens for SpannedValue<T> {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let SpannedValue { span, ref value } = self;
        tokens.extend(quote_spanned!(span=> #value));
    }
}
```

**Comment by dtolnay** [comment]
Got it -- I would be surprised to see this in a Path that was parsed from somewhere, but in this case the Path is not from parsing.

Does it need to be a Path? Usually only Syn should be building syntax tree nodes. Macros should be building everything as TokenStreams. Appending a segment to a path as a TokenStream looks like:

```rust
path = quote_spanned!(span=> #path :: suffix);
```

**Comment by TedDriggs** [comment]
[Here's](https://github.com/TedDriggs/serde_default/blob/master/src/codegen.rs#L94) an example of where I'm using the `Path`. I do this so that I can separately test the attribute parsing and the code generation, with type safety ensuring I don't introduce syntax errors between the two halves.

**Comment by dtolnay** [comment]
For type safety I would consider using a newtype that holds tokens of a path:

```rust
struct FieldPath(TokenStream);
```

In any case, here is a basic way to respan a node:

```rust
use proc_macro2::Span;
use quote::{quote, ToTokens};
use syn::parse::Parse;
use syn::LitStr;

fn respan<T: ToTokens + Parse>(node: &T, span: Span) -> T {
    let tokens = quote!(#node);
    let string = tokens.to_string();
    let lit = LitStr::new(&string, span);
    lit.parse().unwrap()
}
```

**Comment by dtolnay** [comment]
I like your implementation a lot but it's off the beaten path of ways that I have personally used Syn. :) So there is going to need to be some amount of figuring out of new idioms.

**Comment by TedDriggs** [comment]
Yeah, I tried to make attribute parsing feel more like deserializing with `serde`. For a while I didn't worry about error locations, but when I noticed that `serde` was doing them properly I felt compelled to go back and make it "just work" with `darling`.

**Comment by dtolnay** [comment]
Closing because I don't intend to add a `quote_force_span!` sort of API to this crate.
