### ISSUE TITLE
Add `ToTokens` for tuples

### ISSUE THREAD

**Issue by orlp** [dtolnay/quote#96]
I am aware of this discussion: https://github.com/dtolnay/quote/issues/54

I don't think it's a sufficient argument to remove tuple support. Having to remap tuples to quoted tuples every time is annoying.

**Comment by dtolnay** [comment]
I would prefer not to make this change.

If mapping tuples to tokens appears overwhelmingly often in your code, it may help to define a newtype in a separate crate that provides the ToTokens impls:

```rust
pub struct Tuple<T>(pub T);

impl<A: ToTokens> ToTokens for Tuple<(A,)> {...}
impl<A: ToTokens, B: ToTokens> ToTokens for Tuple<(A, B)> {...}
impl<A: ToTokens, B: ToTokens, C: ToTokens> ToTokens for Tuple<(A, B, C)> {...}
```

**Comment by ModProg** [comment]
Would it maybe be possible to support the `#(#tuple)*` syntax for tuples? I'm not sure what the underlying logic in quote is, but that would work around the concerns in #54.
